package errors

// func trycatchfun() {
// 	user, err := getUser()
// 	if err != nil {
// 		fmt.Println(err)
// 		return
// 	}
// 	// use user object here.
// 	profile, err := getUserProfile(user.ID)
// 	if err != nil {
// 		fmt.Println(err)
// 		return
// 	}
// }

// func getUser() (User, error) {
// 	// do some get user logic here

// }
